services:
  template:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: weatherspond-service
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 8081:8080
    depends_on:
      - redis
    networks:
      - local
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - local

networks:
  local:
    driver: bridge
    name: local